### ISSUE TITLE
Add access_token for authenticated users to Susi Server Requests

### ISSUE THREAD

**Issue by betterclever** [fossasia/susi_iOS#117]
**Actual Behaviour**

Currently, when a user is authenticated, his access token is saved but is not added as a parameter to Chat API for Susi Server. Thus, Susi Server treats authenticated and unauthenticated users the same.

**Expected Behaviour**

The access_token must be added as a parameter to requests for Authenticated users.

**Steps to reproduce it**

https://github.com/fossasia/susi_iOS/blob/master/Susi/Controllers/MainViewController/MainVCMethods.swift#L129-L139

access_token Parameter must be added here in request.

**Would you like to work on the issue?**

No

**Comment by chashmeetsingh** [comment]
@betterclever issue fixed.
