### ISSUE TITLE
UI Issues: Skip button and Forgot Password Buttons are overlapping

### ISSUE THREAD

**Issue by betterclever** [fossasia/susi_iOS#131]
**Actual Behaviour**

The Skip and Forgot Password buttons are overlapping

**Expected Behaviour**

The buttons should not overlap

**Steps to reproduce it**

Open the sign in screen.

**LogCat for the issue**

N/A

**Screenshots of the issue**

![whatsapp image 2017-07-02 at 10 42 36 pm](https://user-images.githubusercontent.com/16309034/27772292-b1ed6b6c-5f7c-11e7-9967-76cbcffc7c6f.jpeg)

**Would you like to work on the issue?**

No

**Comment by chashmeetsingh** [comment]
fixed in https://github.com/fossasia/susi_iOS/pull/138
