### ISSUE TITLE
Images do not get dislayed when docs are built using yaydoc

### ISSUE THREAD

**Issue by pri22296** [fossasia/susi_iOS#211]
**Actual Behaviour**

The images do not get displayed when building docs using yaydoc

**Expected Behaviour**

They should be displayed

**Screenshots of the issue**

![screenshot 214](https://user-images.githubusercontent.com/11555869/29493366-de991908-85b1-11e7-810c-8cbdb0715f04.png)

**Would you like to work on the issue?**

Yes

**Comment by chashmeetsingh** [comment]
@pri22296 please replace the current images with the ones here: http://imgur.com/a/QSIeo
