### ISSUE TITLE
Create an ipa branch and add regular builds for iOS

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_iOS#22]
Please create an ipa branch and add the app here regularly.

**Comment by chashmeetsingh** [comment]
@mariobehling We need this branch basically to store the ipa files generated for each iteration right, similar to what is done currently in susi_android ?

**Comment by niranjan94** [comment]
@chashmeetsingh that is correct.

**Comment by chashmeetsingh** [comment]
Great!

**Comment by chashmeetsingh** [comment]
@niranjan94 these builds need to be signed so, should I use my team Id to do so?
