### ISSUE TITLE
Revamping for xcode 9

### ISSUE THREAD

**Issue by abdulsamad234** [fossasia/susi_iOS#227]
**Actual Behaviour**

App doesn't run and gives an error of 'Ambiguous use of title' on line 22 of TrainingVCMethods.swift
App doesn't run and gives an error of 'Ambiguous use of title' on line 20 of ResetPasswordVCMethods.swift
Note: This issue now includes all the occurences of navigationItem.title = ... and they all have now been changed to navigationItem.titleLabel.text.

**Expected Behaviour**

App was supposed to run, guess it was a bug in xcode 9. But i have fixed it and i'll be building for ios 11.

**Steps to reproduce it**

Replace titleLabel with title and you get the error

**Would you like to work on the issue?**
Yes, gladly

**Comment by imjog** [comment]
Hi @chashmeetsingh I am working on this issue!
