### ISSUE TITLE
Handle no network connection

### ISSUE THREAD

**Issue by chashmeetsingh** [fossasia/susi_iOS#230]
**Actual Behaviour**

No indicator shows up.

**Expected Behaviour**

An indicator should show up whenever the internet connection is down.

**Steps to reproduce it**

Try disconnecting from Wifi and sending a message from the chat view.

**Would you like to work on the issue?**

No.

Make use of the Reachability pod

**Comment by dannymout** [comment]
@chashmeetsingh Could you assign me to this issue, I can work on this.

**Comment by chashmeetsingh** [comment]
Sure, go ahead 👍

**Comment by DShivansh** [comment]
is this feature added to the app

**Comment by chashmeetsingh** [comment]
Not yet. If you want you can start working on it.

**Comment by DShivansh** [comment]
should i check whether the app is able to make secure connection with https://api.susi.ai

**Comment by DShivansh** [comment]
@chashmeetsingh should i disable the input text field when there is no connection and make the status bar red instead of blue


Please🙏🙏🙏 tell me cause i have the solution and i only want to cosmetically implement it

**Comment by chashmeetsingh** [comment]
Check my comment on gitter. Also, work on the issue and send a PR, will review as soon as possible.
