### ISSUE TITLE
Add skill rating and content type in skill detail view

### ISSUE THREAD

**Issue by chashmeetsingh** [fossasia/susi_iOS#232]
**Actual Behaviour**

Currently, it's not there.

**Expected Behaviour**

It should be present.

**Would you like to work on the issue?**

No.

Refer the image below:
![skill_detail](https://user-images.githubusercontent.com/8962264/31070549-62b9f372-a77e-11e7-9d8d-40ed67f94edd.png)

**Comment by yashLadha** [comment]
I would like to work on this issue.

**Comment by chashmeetsingh** [comment]
Sure, go ahead👍

**Comment by yashLadha** [comment]
Sorry for that. Can it be setup on linux?

**Comment by chashmeetsingh** [comment]
It requires a Mac. I am not sure if you can install Mac OS through virtual box on Linux, check that.

**Comment by lukiee555** [comment]
I would like to work on this if @yashLadha  you are not able to setup this to your system ?

**Comment by DShivansh** [comment]
@chashmeetsingh where will i get this rating and content type from is it available on the susi api

**Comment by DShivansh** [comment]
@chashmeetsingh i have done all the thing now i need some cosmetic help that when positive and negative are <null> in json then should i show positive and negative to be 0 or should i hide them
and in the json it is only given that whether the content is dynamic or not in boolean terms so when the dynamic content is false then should i show content type: non-dynamic or something else

please help🙏

**Comment by chashmeetsingh** [comment]
I think you should show both of them. Add a green up Arrow for positive with account. Same goes for the negative rating but with a down arrow which is red.

**Comment by DShivansh** [comment]
@chashmeetsingh i mean that when there is null given in positive and negative then should i show 0 or should i hide the positive and negative index

i am not abel to understand what you mean in the above comment

**Comment by chashmeetsingh** [comment]
Show 0 for now.
