### ISSUE TITLE
Show Login in Settings when user skip login

### ISSUE THREAD

**Issue by imjog** [fossasia/susi_iOS#265]
**Actual Behaviour**

When we enter in the app by Skip the login, it shows **Logout** in settings. (As in screenshot below)

**Expected Behaviour**

It should be showing Login instead. When the user comes by skipping the login in the app, it should show **Login** in settings.

**Screenshots of the issue**
<img src="https://user-images.githubusercontent.com/20956124/36845377-7a4f51d4-1d7c-11e8-9d6e-837cdcf4eaec.png" width="200">

**Would you like to work on the issue?**

Yes

**Comment by baquer** [comment]
No need of login required here. As far as I know skip button is only for developer convenience, 
Clear this from @chashmeetsingh.

**Comment by chashmeetsingh** [comment]
Skip is basically for anonymously using the app. I remember I had removed logout when skip was clicked not sure how it came back. So what needs to be done is, in case of skip show login there clicking on which goes back to the login screen. That's all for now.

**Comment by imjog** [comment]
Thank you @chashmeetsingh I will make PR for this.
