### ISSUE TITLE
Add Settings button on Chat screen

### ISSUE THREAD

**Issue by imjog** [fossasia/susi_iOS#278]
**Actual Behaviour**

To go to the Settings screen user have to go through Susi Skills page.

**Expected Behaviour**

There should be an option to go to Settings screens directly from Chat screen rather than going from Skills page.

**Steps to reproduce it**

Add a Settings button on the top left of the Chat screen (As shown in the screenshot). Clicking on this button open the Settings screen.

**Screenshots of the issue**

![settingsbutton](https://user-images.githubusercontent.com/20956124/37921112-746bd430-3146-11e8-931e-ae30e514b744.png)

**Would you like to work on the issue?**

Yes

**Comment by SIMRAN1** [comment]
@imjog If you don't mind could I work on this issue?

**Comment by SIMRAN1** [comment]
okk @imjog !!

**Comment by imjog** [comment]
@mariobehling Please close the issue :-)
