### ISSUE TITLE
UI enhancement of Login, SignUp Screen

### ISSUE THREAD

**Issue by ishaan1995** [fossasia/susi_iOS#28]
UI Issues:
1.Susi logo and email field spacing gets abrupt on smaller devices like iPhone 5s. - Login Screen
2.Password invalid texts gets overlapped with confirm password field. - Signup Screen.
3.Keyboard return does not hide the keyboard. - Login, SignUp Screen.
4.Tapping on empty space to hide keyboard - Login, SignUp Screen.

Solution:
1.Change constraints of the UI elements in Login, SignUp Controller
2.Add gesture for tap, and dismiss keyboard on tap gesture.
3.Add keyboard return button functionality to dismiss keyboard.

I would like to fix this issue.

**Comment by chashmeetsingh** [comment]
@ishaan1995 close this issue as it got fixed by #30
