### ISSUE TITLE
Add github commands in README.md

### ISSUE THREAD

**Issue by SIMRAN1** [fossasia/susi_iOS#286]
**Actual Behaviour**

Git commands are not added to Readme.md.

**Expected Behaviour**

Git commands should be added to Readme.md so that it helps newcomers to contribute in app.

**Would you like to work on the issue?**
Yes I would like to work on this issue.

**Comment by SIMRAN1** [comment]
@chashmeetsingh @mariobehling please see to this issue!

**Comment by imjog** [comment]
@SIMRAN1 You added that to Open Event iOS Readme. The same thing would be good here too.
