### ISSUE TITLE
Code signing causes build failure

### ISSUE THREAD

**Issue by chashmeetsingh** [fossasia/susi_iOS#32]
Code signing being turned on sometimes causes Travis build failures

**Comment by Abhi2424shek** [comment]
Hey I was eager to ask why so it works sometimes

**Comment by chashmeetsingh** [comment]
I am confused myself. I was trying for various builds and it worked fine for the initial ones then stopped having a build success until code signing was turned off. 

Any help from any experienced one would be appreciated.

**Comment by chashmeetsingh** [comment]
@Abhi2424shek check now the build passed no idea how.

**Comment by Abhi2424shek** [comment]
So, have you fixed it? I don't know much about Travis's certificate key signing, I see that in the issue they are asking to import dev credentials, have you done it?

**Comment by chashmeetsingh** [comment]
Yep, switching that off would work for everyone. I know they asked for dev credentials but wasn't sure if I should continue with my dev account. What do you think?

Also, unless a paid dev account is active we can't even use background services, notifications or anything.

**Comment by Abhi2424shek** [comment]
I think someone like @mariobehling would provide you a dev account, I guess and hope so, can't I hope?

**Comment by chashmeetsingh** [comment]
I removed code signing for the last commit so that we can check if it will actually work until we get a dev cert for the app.

**Comment by ishaan1995** [comment]
Did you try using CODE_SIGN_IDENTITY="" value as well in travis config like ->
xcodebuild test -workspace Susi.xcworkspace CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -scheme Susi -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0'

**Comment by chashmeetsingh** [comment]
When code signing is turned off CODE_SIGN_IDENTITY is automatically set to an empty string

**Comment by chashmeetsingh** [comment]
@Abhi2424shek I skipped code signing check and the build passed, should we merge now?
