### ISSUE TITLE
Modify the UI of 'Reset Password' screen

### ISSUE THREAD

**Issue by jogendra** [fossasia/susi_iOS#325]
**Actual Behaviour**

UI is not consistent with UI of login, signup and forgot password activity (see in the screenshot below)

**Expected Behaviour**

UI of Reset password screen should be same as login, signup and forgot password screens

**Steps to reproduce it**

Go to 'Settings > Reset password'

**Screenshots of the issue**

![simulator screen shot - iphone 8 - 2018-06-07 at 16 37 42](https://user-images.githubusercontent.com/20956124/41096571-ae558eba-6a72-11e8-81c5-be9aa3b6072c.png)

**Would you like to work on the issue?**

Yes

**Comment by tusharjindal353** [comment]
sir i want to work on this issue.if you can allow.Please

**Comment by imjog** [comment]
@tusharjindal353 As you can see above there is already Pull Request for this.

**Comment by tusharjindal353** [comment]
Any other issues which i can work on??

**Comment by tusharjindal353** [comment]
thanks/sirji
