### ISSUE TITLE
Send country name and country code in chat.json API

### ISSUE THREAD

**Issue by AnupKumarPanwar** [fossasia/susi_iOS#331]
**Actual Behaviour**

Only latitude and longitude are send as API parameters.

**Expected Behaviour**

Country code and country name are also required to get country wise usage analytics.
Refer to this PR : https://github.com/fossasia/susi_server/pull/811

**Steps to reproduce it**

NA

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

I think @imjog  can solve it.

**Comment by imjog** [comment]
@AnupKumarPanwar Yes, I am sending a PR soon. Thank you :)
