### ISSUE TITLE
Send device type in chat.json API

### ISSUE THREAD

**Issue by AnupKumarPanwar** [fossasia/susi_iOS#334]
The type of device ie, "iOS" is  required to get device wise usage analytics.

**Steps to reproduce it**

NA

**LogCat for the issue**

https://api.susi.ai/susi/chat.json?q=hello&language=en&access_token=PGbzC5zYQBQUuCrYrarqIuRe4lvjfn&latitude=30.1667&longitude=77.3

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

Yes

**Comment by tusharjindal353** [comment]
sir i want to code for this issue.

**Comment by AnupKumarPanwar** [comment]
Okay go ahead

**Comment by AnupKumarPanwar** [comment]
@tusharjindal353 is there any progress in it?

**Comment by tusharjindal353** [comment]
sir where i have to send the device type and model??

**Comment by imjog** [comment]
@AnupKumarPanwar I am taking this issue
