### ISSUE TITLE
Display average stars and total ratings on the Skills Home page

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_iOS#336]
**Actual Behaviour**
Not present

**Expected Behaviour**
Display average stars and total ratings on the Skills cards on Home page.

**Screenshots of the issue**
![deepinscreenshot_select-area_20180615104800](https://user-images.githubusercontent.com/12656846/41451256-98a2ddd0-7089-11e8-9108-129f73c6a9ef.png)

**Would you like to work on the issue?**
Anyone can take this up.

**Comment by imjog** [comment]
Please see discussion on correspond SUSI Android issue here: https://github.com/fossasia/susi_android/issues/1401

**Comment by imjog** [comment]
The issue is copy of #335

**Comment by anshumanv** [comment]
Closed #335

**Comment by AnupKumarPanwar** [comment]
@imjog Are so are you working on it?

**Comment by imjog** [comment]
@AnupKumarPanwar Sending a PR soon
