### ISSUE TITLE
Implement feedback system

### ISSUE THREAD

**Issue by SIMRAN1** [fossasia/susi_iOS#339]
**Actual Behaviour**

Currently, the user can only rate a skill. We do not get a detailed feedback from the user as to where the real problem is.

**Expected Behaviour**

There is a need to implement the feedback system (new APIs have been made on the server) in our app to allow the user to submit a subjective feedback so that we can understand where we need to improve and then we can act accordingly to enhance the existing skills.
- [x] Allow the user to post skill feedback
- [x] Display skill feedback

**Screenshots of the issue**
N/A
Corresponding Susi Android issue:- https://github.com/fossasia/susi_android/issues/1388

**Would you like to work on the issue?**

Yes

**Comment by imjog** [comment]
@SIMRAN1 Are you working on this issue?

**Comment by SIMRAN1** [comment]
I will work on it later !!

**Comment by imjog** [comment]
@SIMRAN1 You have to work on it now it is the blockage in other features or should I take this issue?

**Comment by SIMRAN1** [comment]
Sure You can take this issue. I will work on other issues!
