### ISSUE TITLE
Propose and implement best practices

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_iOS#37]
There are a number of guides for best practices of iOS projects.

E.g. please watch this talk: https://www.cocoanetics.com/2014/10/best-practices-running-an-ios-open-source-project-on-github/

Please add info on best practices for this project into the Readme.md.

**Comment by chashmeetsingh** [comment]
Sure. Will take a look 👍

**Comment by imjog** [comment]
Here is a link for iOS best practices:
 https://github.com/futurice/ios-good-practices.
For Swift Style guide please have a look at [LinkedIn Swift Style Guide](https://github.com/linkedin/swift-style-guide)

@mariobehling @chashmeetsingh your views?
