### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_iOS#38]
The Readme.md is not super long. Therefore for now we can keep all the current documentation here. Please add set up instructions into the main Readme.md.

Secondly, please change the link to the mailing list to https://groups.google.com/forum/#!forum/opntec-dev

**Comment by chashmeetsingh** [comment]
Setup instructions already in the main README.

Will send a PR for the mailing list in some time.

**Comment by mariobehling** [comment]
https://github.com/fossasia/susi_iOS/blob/master/docs/iOS_App_Setup.md -> Readme.md

**Comment by chashmeetsingh** [comment]
Sure
