### ISSUE TITLE
Anonymize Feedback section and add avatar

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_iOS#399]
- [x] The feedback section currently shows complete email addresses. Please anonymize the feedback and only show emails until the @ sign, e.g. "mariobehling@..".
- [x] Add user gravatar on the image placeholder

CMS issue ref - https://github.com/fossasia/susi_skill_cms/issues/1132

**Would you like to work on the issue?**
No

**Comment by akshatnitd** [comment]
@imjog Would you take this up?

**Comment by imjog** [comment]
@akshatnitd Yes, sending a PR soon.
