### ISSUE TITLE
Allow editing of smart speaker setting

### ISSUE THREAD

**Issue by jogendra** [fossasia/susi_iOS#418]
**Actual Behaviour**

There is no option to editing the setting of currently connected SUSI.AI Smart Speaker

**Expected Behaviour**

Allow editing of smart speaker setting

**Screenshots of the issue**
N/A

**Would you like to work on the issue?**

Yes

**Comment by raghavbabbar** [comment]
@jogendra  can you please explain this issue in detail?

**Comment by jogendra** [comment]
@raghavbabbar the method to connecting SUSI smart speaker to mobile is changed. Check susi hardware channel. Closing this issue.
