### ISSUE TITLE
Logout button is not working sometime

### ISSUE THREAD

**Issue by jogendra** [fossasia/susi_iOS#431]
**Actual Behaviour**

Sometime Logout button in settings does not work.

**Steps to reproduce it**

Go to _Settings > Logout_

**Screenshots of the issue**
N/A

**Would you like to work on the issue?**

@hashah88 Can you take up this issue?

**Comment by hashah88** [comment]
Yes, I can.

**Comment by jogendra** [comment]
@hashah88 Great. Go ahead :)

**Comment by jogendra** [comment]
@hashah88 since we are not getting the update from you, I am start working on this as we are releasing the app to App Store.
