### ISSUE TITLE
Implement the 3D Touch Home Screen Quick Actions

### ISSUE THREAD

**Issue by jogendra** [fossasia/susi_iOS#436]
**Expected Behaviour**
Implement 3D touch home screen quick actions to instantly access some feature from 3D touch

**Screenshots of the issue**

N/A

**Would you like to work on the issue?**

Yes

**Comment by AnuritaS** [comment]
Hey, @jogendra I would like to help on this issue and work on it.

**Comment by jogendra** [comment]
Sure @AnuritaS. Go ahead :)
