### ISSUE TITLE
Implement Pull to Refresh feature on Skill Listing

### ISSUE THREAD

**Issue by jogendra** [fossasia/susi_iOS#462]
**Actual Behaviour**

There isn't any way to refresh skills from skill listing screen.

**Expected Behaviour**

Add pull to refresh feature on the skill listing screen that can reload the data on pull

**Steps to reproduce it**

Chat > Skill Listing

**LogCat for the issue**

N/A

**Screenshots of the issue**

N/A

**Would you like to work on the issue?**

Anyone can take up this issue

**Comment by jogendra** [comment]
@raghavbabbar Yeah sure :)

**Comment by raghavbabbar** [comment]
@jogendra  i am working on this now.
