### ISSUE TITLE
Sign up page dismiss keyboard

### ISSUE THREAD

**Issue by s4rv4d** [fossasia/susi_iOS#496]
**Actual Behaviour**
While dismissing the keyboard it crashes because the tap gesture is using the loginvc's dismiss keyboard functions
**Expected Behaviour**
It shouldn't crash while dismissing 

**Steps to reproduce it**

Tap on one of the textfields and then tap back on the main view to dismiss keyboard

**LogCat for the issue**

libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

**Screenshots of the issue**

nil
**Would you like to work on the issue?**

I would like to work on this issue if possible

**Comment by jogendra** [comment]
Resolved in #495
