### ISSUE TITLE
Ability to create lists from JSON

### ISSUE THREAD

**Issue by chashmeetsingh** [fossasia/susi_iOS#50]

**Comment by chashmeetsingh** [comment]
![screen shot 2017-05-10 at 1 04 08 am](https://cloud.githubusercontent.com/assets/8962264/25869343/989d0b38-351d-11e7-9d76-1df3b924d872.png)

@mariobehling looks good design wise?
What images are you referring to? These aren't links as the data object obtained from the API call returns only titles and no Urls for the same. Should we also add URLs in response and make them links?

**Comment by mariobehling** [comment]
The heading says ability to add tables. This is not a table but a list. 

@Orbiter What do you expect as an output here?

> Should we also add URLs in response and make them links?

I think URLs would be great. Please open an issue in the server and we check what others say. Thanks.

**Comment by chashmeetsingh** [comment]
sure!

**Comment by chashmeetsingh** [comment]
Actually, it's a table. The actions type says it's a table:
```
"actions": [
      {
        "type": "answer",
        "expression": "Here is the list of articles about loklak"
      },
      {
        "type": "table",
        "columns": ["title"]
      }
    ]
```
