### ISSUE TITLE
Crash On Chat VC

### ISSUE THREAD

**Issue by raghavbabbar** [fossasia/susi_iOS#514]
The crash occur when there is Api success and still gets no data

**Comment by chashmeetsingh** [comment]
Can you share some example query for this?

**Comment by raghavbabbar** [comment]
> Can you share some sample query for this?

Hi @chashmeetsingh . i got this crash when i was just roughly sending meaningless text!!.  i donot remember what text exactly made a crash. well i will try to figure out
