### ISSUE TITLE
Add option to choose a different susi server

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_iOS#72]
Add custom url support similar to android app. ref [issue](https://github.com/fossasia/susi_android/issues/520) [PR](https://github.com/fossasia/susi_android/pull/572). Add option to either select susi default server or custom server. If user chooses custom server, ask for Base url of the server. 
Also add an option to change server in settings. In that option simply log out the user. Check screenshot in the referred PR for more details.

**Comment by chashmeetsingh** [comment]
Fixed. Please close this Issue, thanks! @chiragw15
