### ISSUE TITLE
App is crashing sometimes when reply is websearch type

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_iOS#84]
**Actual Behaviour**

App is crashing when user send message like below heaven, slow speed where susi reply is websearch type.

**Expected Behaviour**

App should not crash.

**Steps to reproduce it**

Start susi iOS app and send messages like below heaven, slow speed where reply is websearch type but app is not able to find something on web.

**LogCat for the issue**

@chashmeetsingh can you provide logcat? I can't do this.

**Screenshots of the issue**

**Would you like to work on the issue?**

@chashmeetsingh try to solve it.

**Comment by chashmeetsingh** [comment]
Please provide a sample query you used?

**Comment by amitiwary999** [comment]
Query:
Me: Go to hell
Susi reply: where it is?
Me: Below heaven
App crash

**Comment by chashmeetsingh** [comment]
Ok will take a look

**Comment by chashmeetsingh** [comment]
@amitiwary999 updated the new version on Appetize.io in case you need to take a look.
