### ISSUE TITLE
Currently for play video command susi reply side remain blank

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_iOS#85]
**Actual Behaviour**

On giving play video command some random video start playing but susi reply side remain blank. Currently in Android part susi reply side show text playing video.

**Expected Behaviour**

Some text should be shown. In Android part I am trying to change it in thumbnail image or some url text.

**Steps to reproduce it**

Give Play video command.

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**
![screenshot_2017-06-03-18-46-34](https://cloud.githubusercontent.com/assets/14003244/26753875/ae5ed856-488d-11e7-8d4d-b293e63bef1b.png)

**Would you like to work on the issue?**

@chashmeetsingh

**Comment by chashmeetsingh** [comment]
random as in? I am using youtube's data API to search the videos, first one that comes up is used.

What should be shown in the text part? Let me know what is being currently implemented will do that directly for Susi response instead of fixing anything up here :)

@amitiwary999

**Comment by amitiwary999** [comment]
Like currently in Android app we show text playing video in susi response side. So chat will be like
User: play video
(Some video start playing)
Susi: playing video

**Comment by amitiwary999** [comment]
I am trying to change that playing video reply . Instead of text we can show thumbnail image of that you tube video.

**Comment by chashmeetsingh** [comment]
Great, let's add the thumbnail image directly then.

**Comment by chashmeetsingh** [comment]
Hey @amitiwary999 is the below image what is required? We are able to play images from these images or the previous one it comes automatically as a pop up?

![screen shot 2017-06-05 at 10 40 21 pm](https://cloud.githubusercontent.com/assets/8962264/26794663/3793cbaa-4a40-11e7-8ee8-325b5d6b52c3.png)

**Comment by chashmeetsingh** [comment]
@amitiwary999 please close this issue for now.
